### PR TITLE
shell: return status for moveitemtotrash operation

### LINKED ISSUE #1014: Shell.moveItemToTrash should return boolean for success or not
On Windows when I lock a file (LockFile.exe is a tool for this) and then try to delete the file using Shell.moveItemToTrash, this operation fails silently. Ideally I get an error from the method call, but I would also benefit from a simple boolean telling me if the delete actually happened or not.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1014 , but any reason not use `base::DeleteFile` instead for all platforms ?

### CODE REVIEW

File: atom/common/platform_util_win.cc [hunk 1]
```diff
@@ -164,7 +164,12 @@ void OpenExternal(const GURL& url) {
   }
 }
 
-void MoveItemToTrash(const base::FilePath& path) {
+bool MoveItemToTrash(const base::FilePath& path) {
+  // On XP SHFileOperation will return ERROR_ACCESS_DENIED instead of
```
Comment (paulcbetts) [inline atom/common/platform_util_win.cc]: Atom Shell doesn't even boot on < Win7, you can probably forget about this

File: atom/common/platform_util_win.cc [hunk 2]
```diff
@@ -176,7 +181,21 @@ void MoveItemToTrash(const base::FilePath& path) {
...
+  // happen).  See MSDN for SHFileOperation and SHFILEOPTSTRUCT.
+  if (file_operation.fAnyOperationsAborted)
+    return false;
+
+  // Some versions of Windows return ERROR_FILE_NOT_FOUND (0x2) when deleting
+  // an empty directory and some return 0x402 when they should be returning
+  // ERROR_FILE_NOT_FOUND. MSDN says Vista and up won't return 0x402.  Windows 7
+  // can return DE_INVALIDFILES (0x7C) for nonexistent directories.
+  return (err == 0 || err == ERROR_FILE_NOT_FOUND || err == 0x402 ||
+          err == 0x7C);
```
Comment (paulcbetts) [inline atom/common/platform_util_win.cc]: Can we just use the constants here? Why use 0x7C?

**Comment by deepak1556** [comment]
fixed, thanks!

File: atom/common/platform_util_win.cc (hunk 1 above)
Comment (deepak1556) [inline atom/common/platform_util_win.cc]: haha :)

**Comment by paulcbetts** [comment]
LGTM

**Comment by zcbenz** [comment]
`base::DeleteFile` removes the file, instead of moving the file to trash.

File: atom/common/platform_util.h [hunk 3]
```diff
@@ -26,7 +26,11 @@ void OpenItem(const base::FilePath& full_path);
 void OpenExternal(const GURL& url);
 
 // Move a file to trash.
-void MoveItemToTrash(const base::FilePath& full_path);
+#if defined(OS_WIN)
```
Comment (zcbenz) [inline atom/common/platform_util.h]: We should also return `bool` on Linux and OS X otherwise the API will return different types on different platforms.

And can you also add documents on `moveItemToTrash`'s new behavior?

Comment (deepak1556) [inline atom/common/platform_util.h]: sure, thanks for the clarification!

**Comment by deepak1556** [comment]
Made the changes but need to test on linux.

**Comment by deepak1556** [comment]
Need to fix the linux api, as currently it returns the state of launchprocess and not the status of the operation.

**Comment by zcbenz** [comment]
> Need to fix the linux api, as currently it returns the state of launchprocess and not the status of the operation.

The exit code of `gvfs-trash` should be enough to determine whether the operation succeeded, but you also need to ensure the process completed before getting the exit code.

File: atom/common/platform_util_linux.cc [hunk 4]
```diff
@@ -13,7 +13,8 @@
 
 namespace {
 
-void XDGUtil(const std::string& util, const std::string& arg) {
+void XDGUtil(const std::string& util, const std::string& arg,
```
Comment (zcbenz) [inline atom/common/platform_util_linux.cc]: We don't actually need the exit code, we only need to know whether the operation succeeded. So `XDGUtil` can just return `bool` to indicate whether the operation succeeded.

Comment (deepak1556) [inline atom/common/platform_util_linux.cc]: Done, thanks!

**Comment by zcbenz** [comment]
Thanks!
