### PR TITLE
webContents: workaround reloadIgnoringcache without breaking node integration

### LINKED ISSUE #1379: BrowserWindow.reloadIgnoringCache() does not ignore cache
The [documentation for `BrowserWindow.reloadIgnoringCache` states](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#webcontentsreloadignoringcache)
> Reloads current page and ignores cache.

In practice, this method behaves exactly like `BrowserWindow.reload` and does not ignore the cache when reloading.  This occurs at least on Atom-shell v0.22.2 and v0.22.3, and can be observed through the dev tools' Network tab.

A minimal Atom-shell app that demonstrates this behavior can be found [in this gist](https://gist.github.com/mark-wagon/948a3d0cf17d88c9a89c).  Repro steps are outlined in the gist's readme.

### PR DESCRIPTION
**Pull request by deepak1556**
fixes #1379

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -387,6 +387,9 @@ void WebContents::Reload(const mate::Dictionary& options) {
 }
 
 void WebContents::ReloadIgnoringCache(const mate::Dictionary& options) {
+  // hack to remove pending entries that ignores cache and treated as a fresh
```
Comment (zcbenz) [inline atom/browser/api/atom_api_web_contents.cc]: "hack" => "Hack".

Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: Fixed, thanks!

**Comment by zcbenz** [comment]
:sparkle:
