### PR TITLE
shell: fix regression for moveItemToTrash on mac

### LINKED ISSUE #1385: Shell.moveItemToTrash returns false if operation suceeds and true otherwise on mac
Is this just me or is the flag wrong on Mac for this operation? I get "false" returned but the file I delete moves to trash. When I run the same code again I get "true" returned.

I would expect the opposite for status if the operation failed or not.

### PR DESCRIPTION
**Pull request by deepak1556**
fixes #1385 , sorry my bad.

### CODE REVIEW

File: atom/common/platform_util_mac.mm [hunk 1]
```diff
@@ -140,7 +140,7 @@ bool MoveItemToTrash(const base::FilePath& full_path) {
   if (!path_string || !file_array || !status)
     LOG(WARNING) << "NSWorkspace failed to move file " << full_path.value()
                  << " to trash";
-  return (status == 0);
+  return (!!status);
```
Comment (zcbenz) [inline atom/common/platform_util_mac.mm]: I think we should just use `BOOL` for `status`'s type.

Comment (deepak1556) [inline atom/common/platform_util_mac.mm]: Fixed, thanks!
